---
title: KeyMagic
timezone: Asia/Rangoon
collections:
  downloads:
    title: Downloads
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: downloads
  values:
    layout: download
- scope:
    path: ''
    type: pages
  values:
    layout: page
description: Smart Complex Script IME
theme: minima
permalink: pretty
header_pages:
  - downloads.markdown
  - installation.markdown
  - faq.markdown
  - github.markdown
google_analytics: UA-5530678-2